name: Lint

on: [push]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 18
